using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardLists
{
    public  List<CardData> HumanityDeck;
    public  List<CardData> TitansDeck;
     public CardLists()
    {
        HumanityDeck = new List<CardData>();
        TitansDeck= new List<CardData>();
       
        CardData armin = ScriptableObject.CreateInstance<CardData>();
        CardData ataquenocturno = ScriptableObject.CreateInstance<CardData>();
        CardData estrategiaErwin = ScriptableObject.CreateInstance<CardData>();
        CardData connie = ScriptableObject.CreateInstance<CardData>(); 
        CardData EM3D = ScriptableObject.CreateInstance<CardData>();
        CardData eren = ScriptableObject.CreateInstance<CardData>();
        CardData erwin = ScriptableObject.CreateInstance<CardData>();       
        CardData estrategiaLevi  = ScriptableObject.CreateInstance<CardData>();
        CardData fleger = ScriptableObject.CreateInstance<CardData>();
        CardData gabi = ScriptableObject.CreateInstance<CardData>();
        CardData hange = ScriptableObject.CreateInstance<CardData>();
        CardData hannes = ScriptableObject.CreateInstance<CardData>();
        CardData historia = ScriptableObject.CreateInstance<CardData>();
        CardData jean = ScriptableObject.CreateInstance<CardData>();
        CardData levi = ScriptableObject.CreateInstance<CardData>();
        CardData marco = ScriptableObject.CreateInstance<CardData>();
        CardData magaly = ScriptableObject.CreateInstance<CardData>();
        CardData maniobradeDistraccion = ScriptableObject.CreateInstance<CardData>();
        CardData mikasa = ScriptableObject.CreateInstance<CardData>();
        CardData nanaba = ScriptableObject.CreateInstance<CardData>();
        CardData petra = ScriptableObject.CreateInstance<CardData>(); 
        CardData refuerzodeTrost = ScriptableObject.CreateInstance<CardData>();
        CardData sasha = ScriptableObject.CreateInstance<CardData>();
        CardData takami = ScriptableObject.CreateInstance<CardData>();
        CardData ymir = ScriptableObject.CreateInstance<CardData>();
        
        armin.Initialize("Armin Arlet", "Carta de Héroe: Estratega capaz de cambiar el rumbo de la batalla con su agudo intelecto, unificando las fuerzas de todos los guerreros para vencer", 8, Row.distantRow, 1,null);
        ataquenocturno.Initialize("Ataque Nocturno", "Carta Clima: Ataque sorpresa nocturno que debilita la primera linea enemiga, reduciendo el poder de las cartas con capacidad de ataque 4 o inferior a 0.", 0, Row.W_attack, 2,null);
        estrategiaErwin.Initialize("Estrategia de Erwin", "Carta Incremento: Moviliza todas las unidades para una carga decisiva, impulsando el espíritu combativo del ejercito aumentando en su poder el poder de cada carta en la fila", 3, Row.siegeRow, 3,null);
        connie.Initialize("Connie Springer", "Carta de Unidad: Rápido y ágil, excepcional en ataques veloces.", 4, Row.attackRow, 4,null);
        EM3D.Initialize("Equipamiento de Maniobra Tridimensional", "Carta Incremento: Permite un movimiento y evasión rápidos, esencial para el combate moderno por lo que aumenta la capacidad de ataque de cada carta en su poder.", 2, Row.IsiegeRow, 5,null);
        eren.Initialize("Eren Yeager", "Carta de Héroe: Posee el poder de transformarse y aplastar enemigos con fuerza devastadora.", 11, Row.attackRow, 6,null);
        erwin.Initialize("Erwin Smith", "Carta de Héroe: Su liderazgo aumenta la moral y el poder de todos los aliados en batalla, sacrificara su brazo para eliminar al mas debil del enemigo", 6, Row.attackRow, 7,null);
        estrategiaLevi.Initialize("Estrategia de Levi", "Carta Unidad: Una maniobra táctica que corta las defensas enemigas con precisión quirúrgica.Eliminara facilmente a la fila enemiga con menos cartas", 7, Row.IattackRow, 8,null);
        fleger.Initialize("Flegel Reeves", "Carta de Unidad: Inspira el apoyo local, proporcionando refuerzos y esperanza. Tiene la capacidad de lograr un despeje efectivo", 3, Row.siegeRow, 9,null);
        gabi.Initialize("Gabi Braun", "Carta de Unidad: Joven e imprudente, capaz de daños inesperados y dramáticos. Es un buen recurso que aumentara el poder de los que luchan a su lado", 5, Row.distantRow, 10,null);
        hange.Initialize("Hange Zoë", "Carta de Héroe: Utiliza su conocimiento científico para crear ventajas tácticas", 5, Row.Leader, 11,null);
        hannes.Initialize("Hannes", "Carta de Unidad: Soldado veterano, proporciona una defensa sólida contra los ataques.Puede inhabilitar un clima", 4, Row.attackRow, 12,null);
        historia.Initialize("Historia Reiss", "Carta de Héroe: Empodera y protege a los aliados cercanos con su presencia real.No tiene habilidad especial definida", 5, Row.siegeRow, 13,null);
        jean.Initialize("Jean Kirstein", "Carta de Unidad: Luchador adaptable, eficaz en múltiples escenarios de combate.", 6, Row.attackRow, 14,null);
        levi.Initialize("Levi Ackerman", "Carta de Héroe: Extremadamente letal en el ataque, puede diezmar líneas enemigas enteras.Y en ocasiones si sus tropas lo traicionan tambien las eliminara", 8, Row.attackRow, 15,null);
        magaly.Initialize("Magaly", "Carta de Unidad: Guerrera menos conocida, sorprendentemente eficaz en el combate.", 4, Row.distantRow, 16,null);
        maniobradeDistraccion.Initialize("Maniobra de Distracción", "Carta Clima: Desvía la atención del enemigo,sus incrementos se veran perjudicados, bajando su guardia, pero provoca perdidas de puntos tambien a las cartas que permanecen en la fila propia.", 0, Row.W_distant, 17,null);
        mikasa.Initialize("Mikasa Ackerman", "Carta de Héroe: Combatiente altamente capacitada, inflige daños significativos a sus enemigos.Puede utilizar todas las cartaas del campo para aumentar el poder de cada una en su promedio", 8, Row.attackRow, 18,null);
        nanaba.Initialize("Nanaba", "Carta de Unidad: Experta en movilidad y enfrentamiento con el enemigo.", 4, Row.distantRow, 19,null);
        petra.Initialize("Petra Ral", "Carta de Unidad: Apoya a sus aliados con habilidades que mejoran sus capacidades.Te permite obtener mas apoyo al incrementa 1 carta a tu mano", 4, Row.distantRow, 20,null);
        refuerzodeTrost.Initialize("Refuerzos de Trost", "Carta Incremento: Fortalece la línea más débil, proporcionando apoyo crucial, dandole mas poder a las cartas  de su fila para defender la ciudad.", 1, Row.IdistantRow, 21,null);
        sasha.Initialize("Sasha Blouse", "Carta de Unidad: Francotiradora, puede apuntar a unidades clave enemigas desde la distancia.Podra eliminar a el mas poderoso enemigo desde lejos", 6, Row.distantRow, 22,null);
        takami.Initialize("Takami", "Carta de Unidad: Un personaje menor con un papel en el reconocimiento y la inteligencia.", 3, Row.siegeRow, 23,null);
        ymir.Initialize("Ymir", "Carta de Héroe: Lucha ferozmente por sus amigos, impredecible en la batalla.Es capaz de darlo todo para lograr que la fuerza de sus companeros aumente", 5, Row.attackRow, 24,null);
        marco.Initialize("Marco Bott", "Carta de Unidad: Valiente y con un gran sentido de la justicia, busca proteger a sus compañeros en todo momento.",4 , Row.siegeRow, 25,null);

        HumanityDeck.Add(armin);
        HumanityDeck.Add(ataquenocturno);
        HumanityDeck.Add(estrategiaErwin);
        HumanityDeck.Add(connie);
        HumanityDeck.Add(EM3D);
        HumanityDeck.Add(eren);
        HumanityDeck.Add(erwin);
        HumanityDeck.Add(estrategiaLevi);
        HumanityDeck.Add(fleger);
        HumanityDeck.Add(gabi);
        HumanityDeck.Add(hange);
        HumanityDeck.Add(hannes);
        HumanityDeck.Add(historia);
        HumanityDeck.Add(jean);
        HumanityDeck.Add(levi);
        HumanityDeck.Add(marco);
        HumanityDeck.Add(magaly);
        HumanityDeck.Add(maniobradeDistraccion);
        HumanityDeck.Add(mikasa);
        HumanityDeck.Add(nanaba);
        HumanityDeck.Add(petra);
        HumanityDeck.Add(refuerzodeTrost);
        HumanityDeck.Add(sasha);
        HumanityDeck.Add(takami);
        HumanityDeck.Add(ymir);
        

        
        CardData TitanBestia = ScriptableObject.CreateInstance<CardData>();
        CardData TitanFundador = ScriptableObject.CreateInstance<CardData>();
        CardData TitanAcorazado = ScriptableObject.CreateInstance<CardData>();
        CardData TitanHembra = ScriptableObject.CreateInstance<CardData>();
        CardData TitanColosal = ScriptableObject.CreateInstance<CardData>();
        CardData TitanSantaClaus = ScriptableObject.CreateInstance<CardData>();
        CardData TitanDentada = ScriptableObject.CreateInstance<CardData>();
        CardData TitanGloton = ScriptableObject.CreateInstance<CardData>();
        CardData TitanObervador = ScriptableObject.CreateInstance<CardData>();
        CardData TitanSonriente = ScriptableObject.CreateInstance<CardData>();
        CardData TitanSaltarin = ScriptableObject.CreateInstance<CardData>();
        CardData TitanAgraciado = ScriptableObject.CreateInstance<CardData>();
        CardData TitanCarguero = ScriptableObject.CreateInstance<CardData>();
        CardData TitanMandibula = ScriptableObject.CreateInstance<CardData>();
        CardData TitanMartillodeGuerra = ScriptableObject.CreateInstance<CardData>();
        CardData TitanFalco = ScriptableObject.CreateInstance<CardData>();
        CardData TitanDesCarado = ScriptableObject.CreateInstance<CardData>();
        CardData TitanParlante = ScriptableObject.CreateInstance<CardData>();
        CardData TitanTatin = ScriptableObject.CreateInstance<CardData>();
        CardData CalorSofocante = ScriptableObject.CreateInstance<CardData>();
        CardData Caminos = ScriptableObject.CreateInstance<CardData>();
        CardData ElDespertar = ScriptableObject.CreateInstance<CardData>();
        CardData SuerodeTitan = ScriptableObject.CreateInstance<CardData>();
        CardData FuriaTitan = ScriptableObject.CreateInstance<CardData>();
        CardData LLuviadeRocas = ScriptableObject.CreateInstance<CardData>();
        CardData SuenodeFundador = ScriptableObject.CreateInstance<CardData>();
        CardData RugidodelTitanBestia = ScriptableObject.CreateInstance<CardData>();
        
        TitanBestia.Initialize("Titán Bestia", "Carta de Héroe: Un titán con habilidades devastadoras y control sobre otros titanes menores.", 7, Row.siegeRow,26,null);
        TitanFundador.Initialize("Titán Fundador", "Carta de Héroe: Capaz de alterar la memoria de los humanos y controlar otros titanes.", 9, Row.Leader, 27,null);
        TitanAcorazado.Initialize("Titán Acorazado", "Carta de Héroe: Con una defensa impenetrable y fuerza abrumadora.", 8, Row.attackRow, 28,null);
        TitanHembra.Initialize("Titán Hembra", "Carta de Héroe: Rápida y letal, con habilidades tácticas superiores.", 8, Row.distantRow,9,null);
        TitanColosal.Initialize("Titán Colosal", "Carta de Héroe: Su tamaño y poder pueden destruir fortificaciones enteras al instante.", 10, Row.siegeRow, 30,null);
        TitanSantaClaus.Initialize("Titán Santa Claus", "Carta Especial: Un titán festivo pero peligroso, distribuye caos en lugar de regalos.", 6, Row.W_distant, 31,null);
        TitanDentada.Initialize("Titán Dentada", "Carta de Unidad: Con dientes afilados, ideal para combates cercanos y desgarradores.", 5, Row.attackRow, 32,null);
        TitanGloton.Initialize("Titán Glotón", "Carta de Unidad: Devora todo a su paso, incrementando su fuerza con cada bocado.", 4, Row.attackRow, 33,null);
        TitanObervador.Initialize("Titán Observador", "Carta Especial: Utiliza su altura para proporcionar ventajas estratégicas y visuales.", 3, Row.distantRow,4,null);
        TitanSonriente.Initialize("Titán Sonriente", "Carta de Unidad: Su sonrisa enmascara una ferocidad implacable.", 5, Row.attackRow, 35,null);
        TitanSaltarin.Initialize("Titán Saltarín", "Carta de Unidad: Ágil y difícil de atrapar, salta por el campo de batalla causando estragos.", 4, Row.distantRow,6,null);
        TitanAgraciado.Initialize("Titán Agraciado", "Carta de Unidad: Engaña con su apariencia calmada, pero es mortal en el ataque.", 4, Row.distantRow,7,null);
        TitanCarguero.Initialize("Titán Carguero", "Carta de Unidad: Transporta otros titanes más pequeños al campo de batalla.", 6, Row.siegeRow, 38,null);
        TitanMandibula.Initialize("Titán Mandíbula", "Carta de Unidad: Rápido y con mandíbulas que pueden triturar casi cualquier cosa.", 6, Row.attackRow, 39,null);
        TitanMartillodeGuerra.Initialize("Titán Martillo de Guerra", "Carta de Héroe: Forja armas de energía titánica en el combate.", 7, Row.siegeRow, 40,null);
        TitanFalco.Initialize("Titán Falco", "Carta de Unidad: Un nuevo Titán con habilidades aún desconocidas.", 4, Row.attackRow, 41,null);
        TitanDesCarado.Initialize("Titán Descarado", "Carta de Unidad: Sin reservas en su comportamiento, ataca con desenfreno.", 4, Row.attackRow, 42,null);
        TitanParlante.Initialize("Titán Parlante", "Carta Especial: Negocia o distrae a sus enemigos con palabras antes de atacar.", 3, Row.distantRow,3,null);
        TitanTatin.Initialize("Titán Tatin", "Carta de Unidad: Pequeño pero sorprendentemente fuerte, un titán de bolsillo.", 2, Row.attackRow, 44,null);
        CalorSofocante.Initialize("Calor Sofocante", "Carta de Clima: Aumenta la temperatura del campo de batalla, debilitando a las unidades que estan activas en su fila.", 2, Row.W_siege, 45,null);
        Caminos.Initialize("Caminos", "Carta Especial: Conecta los destinos de todos los titanes, permitiendo maniobras coordinadas.", 2, Row.W_distant, 46,null);
        ElDespertar.Initialize("El Despertar", "Carta Especial: Revive a un titán caído del cementerio al campo de batalla.", 3, Row.siegeRow, 47,null);
        SuerodeTitan.Initialize("Suero de Titán", "Carta Incremento: Transforma temporalmente a los humanos en titanes, aumentando el poder de cada carta en su poder.", 2, Row.IdistantRow, 48,null);
        FuriaTitan.Initialize("Furia de Titán", "Carta Incremento: Incrementa la ferocidad de los titanes en el campo, mejorando su ataque.", 3, Row.IattackRow, 49,null);
        LLuviadeRocas.Initialize("Lluvia de Rocas", "Carta de Clima: Lanza rocas gigantes desde el cielo, dañando a todas las unidades en un área, pero las rocas danan tambien a los titanes en la fila propia que son alcanzados por piedras.", 3, Row.W_attack, 50,null);
        SuenodeFundador.Initialize("Sueño de Fundador", "Carta Clima: Un poderoso efecto que altera el estado del juego, reconfigurando el campo de batalla, al disminuir el poder de cada carta debil colocada en ese tipo de fila que le corresponde a cero.", 3, Row.W_siege, 51,null);
        RugidodelTitanBestia.Initialize("Rugido del Titán Bestia", "Carta de espa: El rugido ensordecedor disminuye la moral enemiga, reduciendo su eficacia.", 2, Row.distantRow, 52,null);
       
        TitansDeck.Add(TitanBestia);
        TitansDeck.Add(TitanFundador);
        TitansDeck.Add(TitanAcorazado);
        TitansDeck.Add(TitanHembra);
        TitansDeck.Add(TitanColosal);
        TitansDeck.Add(TitanSantaClaus);
        TitansDeck.Add(TitanDentada);
        TitansDeck.Add(TitanGloton);
        TitansDeck.Add(TitanObervador);
        TitansDeck.Add(TitanSonriente);
        TitansDeck.Add(TitanSaltarin);
        TitansDeck.Add(TitanAgraciado);
        TitansDeck.Add(TitanCarguero);
        TitansDeck.Add(TitanMandibula);
        TitansDeck.Add(TitanMartillodeGuerra);
        TitansDeck.Add(TitanFalco);
        TitansDeck.Add(TitanDesCarado);
        TitansDeck.Add(TitanParlante);
        TitansDeck.Add(TitanTatin);
        TitansDeck.Add(CalorSofocante);
        TitansDeck.Add(Caminos);
        TitansDeck.Add(ElDespertar);
        TitansDeck.Add(SuerodeTitan);
        TitansDeck.Add(FuriaTitan);
        TitansDeck.Add(LLuviadeRocas);
        TitansDeck.Add(SuenodeFundador);
        TitansDeck.Add(RugidodelTitanBestia);
    }
}
